### ISSUE TITLE
[Feature Request] Remote-Connection for interface on EV3-Brick

### ISSUE THREAD

**Issue by R2D2Hud** [XilefTech/CharlieOSX#18]
I thought a cool feature would is when CharlieOSX is running if you vnced into the robot you would get a basic gui.

**Comment by TheGreyDiamond** [comment]
Or maybe a webserver?

**Comment by XilefTech** [comment]
I already got plans for a webpage that would be hosted on the brick that could use on both your mobile or pc to set up some stuff or even remote control the robot. I personally havn't worked with vnced yet, but I'll definately look into it as an alternative! 

I think I should write all my plans down somewhere in this repo so that you all can see, what is planned for the future ;)

Also, please always write the topic of the issue in the title ;)

**Comment by XilefTech** [comment]
Okay, so I created another [wiki entry](https://github.com/XilefTech/CharlieOSX/wiki/Roadmap) with most of my ideas
